### ISSUE TITLE
感谢大佬制作整合插件

### ISSUE THREAD

**Issue by kedyao** [lifishake/apip#1]
安装后 只开启
豆瓣条目（css+js）CODE:mydouban：  
后台编辑  短代码有了 输入
[mydouban id="34941657" type="movie" nipple="no" /]
发布无显示
douban API KEY 是需要输入吗 但我没有key

**Comment by lifishake** [comment]
> 安装后 只开启
> 豆瓣条目（css+js）CODE:mydouban：
> 后台编辑 短代码有了 输入
> [mydouban id="34941657" type="movie" nipple="no" /]
> 发布无显示
> douban API KEY 是需要输入吗 但我没有key

不是这个这是我自己玩的插件，很多实验功能。这个豆瓣功能已经被弃用了。没有KEY玩不转的。想要玩的话得用myfv那个短代码。[myfv id="x" type="movie" title="梦之安魂曲" img="https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2328516855.jpg" link="https://movie.douban.com/subject/1292270" score="99" abs="导演:达伦·阿伦诺夫斯基;演员:艾伦·伯斯汀,杰瑞德·莱托,詹妮弗·康纳利,马龙·韦恩斯,克里斯托弗·麦克唐纳;类型:剧情;地区:美国;年份:2000;douscore:8.7;nipple:" series="0"/]
其实就是手动敲，放一个框里显示好看而已。编辑的时候把id设成x保存的时候会自动从豆瓣扒一张图回来。
我说的是我从大发那里拉出来的分支。wp-douban-movie。只发布了一个版本那个。

**Comment by kedyao** [comment]
> > 安装后 只开启
> > 豆瓣条目（css+js）CODE:mydouban：
> > 后台编辑 短代码有了 输入
> > [mydouban id="34941657" type="movie" nipple="no" /]
> > 发布无显示
> > douban API KEY 是需要输入吗 但我没有key
> 
> 不是这个这是我自己玩的插件，很多实验功能。这个豆瓣功能已经被弃用了。没有KEY玩不转的。想要玩的话得用myfv那个短代码。[myfv id="x" type="movie" title="梦之安魂曲" img="https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2328516855.jpg" link="https://movie.douban.com/subject/1292270" score="99" abs="导演:达伦·阿伦诺夫斯基;演员:艾伦·伯斯汀,杰瑞德·莱托,詹妮弗·康纳利,马龙·韦恩斯,克里斯托弗·麦克唐纳;类型:剧情;地区:美国;年份:2000;douscore:8.7;nipple:" series="0"/]
> 其实就是手动敲，放一个框里显示好看而已。编辑的时候把id设成x保存的时候会自动从豆瓣扒一张图回来。
> 我说的是我从大发那里拉出来的分支。wp-douban-movie。只发布了一个版本那个。

哦哦哦 看见了 用上了 可以使用 感谢  
我准备参考这个在修改修改https://www.npc.ink/12710.html
